// Code generated by goctl. DO NOT EDIT.
package types

type ListRepoReq struct {
	StartDate string `form:"start_date"`
	EndDate   string `form:"end_date"`
}

type PathRepo struct {
	Repo   string `path:"repo"`
	Status string `path:"status"`
	Name   string `json:"name"`
	Foo    string `form:"foo"`
}

type Pong struct {
	Message string `json:"message"`
}

type RepoAnalysisResp struct {
	Resutl string `json:"result"`
}

type RepoInfo struct {
	Repo       string `json:"repo"`
	Branch     string `json:"branch"`
	Total      int    `json:"total"`
	DeptNameT0 string `json:"dept_name_t0"`
	DeptNameT1 string `json:"dept_name_t1"`
	DeptNameT2 string `json:"dept_name_t2"`
	DeptNameT3 string `json:"dept_name_t3"`
}
