// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"commits/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: pingHandler(serverCtx),
			},
		},
		rest.WithTimeout(200*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/active/:repo/anlysis/:status",
				Handler: submitAnalysisHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/active/list",
				Handler: commitsListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/commits"),
		rest.WithTimeout(3000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
